Repository openshift-assisted/cluster-api-provider-openshift-assisted, pull requests merged in 2024-06, with the labels that each got.

#12 MGMT-17972: add tests to agentbootstrapconfig controller
  Dockerfile
  bootstrap/internal/controller/agent_controller.go
  bootstrap/internal/controller/agentbootstrapconfig_controller.go
  bootstrap/internal/controller/agentbootstrapconfig_controller_test.go
  bootstrap/internal/controller/suite_test.go
  controlplane/internal/controller/agentcontrolplane_controller.go
  controlplane/internal/controller/agentcontrolplane_controller_test.go
  controlplane/internal/controller/clusterdeployment_controller.go
  test/utils/unit.go
  util/log/log.go
Labels: size/XL, jira/valid-reference

#10 set CRDs version to v1alpha1
  PROJECT
  bootstrap-components.yaml
  bootstrap/api/v1alpha1/agentbootstrapconfig_types.go
  bootstrap/api/v1alpha1/agentbootstrapconfigtemplate_types.go
  bootstrap/api/v1alpha1/condition_consts.go
  bootstrap/api/v1alpha1/groupversion_info.go
  bootstrap/api/v1alpha1/zz_generated.deepcopy.go
  bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_agentbootstrapconfigs.yaml
  bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_agentbootstrapconfigtemplates.yaml
  bootstrap/config/manager/kustomization.yaml
  bootstrap/internal/controller/agent_controller.go
  bootstrap/internal/controller/agentbootstrapconfig_controller.go
  bootstrap/internal/controller/agentbootstrapconfig_controller_test.go
  bootstrap/internal/controller/infraenv_controller.go
  bootstrap/internal/controller/suite_test.go
  bootstrap/main.go
  controlplane-components.yaml
  controlplane/api/v1alpha1/agentcontrolplane_types.go
  controlplane/api/v1alpha1/condition_consts.go
  controlplane/api/v1alpha1/groupversion_info.go
  controlplane/api/v1alpha1/zz_generated.deepcopy.go
  controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_agentcontrolplanes.yaml
  controlplane/config/manager/kustomization.yaml
  controlplane/internal/controller/agentclusterinstall_controller.go
  controlplane/internal/controller/agentcontrolplane_controller.go
  controlplane/internal/controller/agentcontrolplane_controller_test.go
  controlplane/internal/controller/clusterdeployment_controller.go
  controlplane/internal/controller/suite_test.go
  controlplane/main.go
  test/utils/unit.go
Labels: size/XL

#14 MGMT-17973: add coverage for infraenv controller
  bootstrap/internal/controller/infraenv_controller.go
  bootstrap/internal/controller/infraenv_controller_test.go
Labels: jira/valid-reference, size/L

#15 MGMT-17971: increase coverage for bootstrap agent controller
  bootstrap/internal/controller/agent_controller.go
  bootstrap/internal/controller/agent_controller_test.go
  bootstrap/internal/controller/agentbootstrapconfig_controller_test.go
  bootstrap/internal/controller/suite_test.go
  test/utils/unit.go
Labels: size/XL, jira/valid-reference

#9 WIP: Add finalizer and deletion logic for agent bootstrapconfig
  bootstrap/api/v1alpha1/agentbootstrapconfig_types.go
  bootstrap/api/v1alpha1/groupversion_info.go
  bootstrap/api/v1alpha1/zz_generated.deepcopy.go
  bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_agentbootstrapconfigs.yaml
  bootstrap/internal/controller/agent_controller.go
  bootstrap/internal/controller/agentbootstrapconfig_controller.go
  bootstrap/main.go
Labels: do-not-merge/work-in-progress, size/L

#21 fix tests in bootstrap provider
  bootstrap/internal/controller/agent_controller.go
  bootstrap/internal/controller/agent_controller_test.go
  bootstrap/internal/controller/agentbootstrapconfig_controller.go
Labels: size/M

#18 MGMT-17963: Enable pull-through cache setup
  controlplane/api/v1alpha1/agentcontrolplane_types.go
  controlplane/api/v1alpha1/zz_generated.deepcopy.go
  controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_agentcontrolplanes.yaml
  controlplane/config/rbac/role.yaml
  controlplane/internal/controller/agentcontrolplane_controller.go
  controlplane/internal/controller/clusterdeployment_controller.go
  controlplane/internal/controller/imageregistry/image_registry.go
  controlplane/internal/controller/imageregistry/image_registry_test.go
  go.mod
  go.sum
Labels: size/XL, jira/valid-reference

#24 NO-ISSUE: Cleanup pull-through cache
  controlplane/internal/controller/clusterdeployment_controller.go
  controlplane/internal/imageregistry/image_registry.go
  controlplane/internal/imageregistry/image_registry_test.go
  docs/image_registry.md
Labels: jira/valid-reference, size/L

#26 extract clusterdeployment definition
  assistedinstaller/agentclusterinstall.go
  assistedinstaller/clusterdeployment.go
  bootstrap/internal/controller/agentbootstrapconfig_controller.go
  controlplane/internal/controller/agentcontrolplane_controller.go
  controlplane/internal/controller/clusterdeployment_controller.go
  util/util.go
Labels: size/L

#27 fix tests in controlplane controller
  controlplane/internal/controller/agentclusterinstall_controller_test.go
  controlplane/internal/controller/agentcontrolplane_controller.go
  controlplane/internal/controller/agentcontrolplane_controller_test.go
  controlplane/internal/controller/suite_test.go
Labels: size/L

#25 MGMT-17981: Refactor controlplane's agentclusterinstaller controller
  controlplane/internal/controller/agentclusterinstall_controller.go
Labels: jira/valid-reference, size/L

#28 MGMT-17981: Add AgentClusterInstall controller unit tests
  controlplane/internal/controller/agentclusterinstall_controller_test.go
Labels: jira/valid-reference

#29 MGMT-18017: Create placeholder pull secret
  assistedinstaller/clusterdeployment.go
  controlplane/internal/controller/agentcontrolplane_controller.go
Labels: size/M, jira/valid-reference

#33 MGMT-18188: Enable pulling images via tag
  controlplane/internal/imageregistry/image_registry.go
  controlplane/internal/imageregistry/image_registry_test.go
Labels: jira/valid-reference, size/L

#32 MGMT-17982: Initial cleanup of AgentControlPlane controller
  controlplane/internal/controller/agentcontrolplane_controller.go
Labels: lgtm, jira/valid-reference, size/L

#37 Improve makefile
  Makefile
  bootstrap-components.yaml
Labels: lgtm, approved, size/M

#38 MGMT-17963: Refactor image registry
  controlplane/internal/controller/clusterdeployment_controller.go
  controlplane/internal/imageregistry/image_registry.go
  controlplane/internal/imageregistry/image_registry_test.go
Labels: size/XL, approved, jira/valid-reference

#36 MGMT-17982: Refactor AgentControlPlane replica logic
  controlplane/internal/controller/agentcontrolplane_controller.go
  util/util.go
Labels: approved, jira/valid-reference, size/L

#42 fix linter and add unit test coverage
  controlplane/internal/controller/agentcontrolplane_controller.go
  controlplane/internal/imageregistry/image_registry_test.go
Labels: approved, size/L

#40 MGMT-17965: Ensure all created resources have owner references
  bootstrap/internal/controller/agentbootstrapconfig_controller.go
  controlplane/internal/controller/agentcontrolplane_controller.go
  controlplane/internal/controller/clusterdeployment_controller.go
Labels: lgtm, size/S, approved, jira/valid-reference

#43 MGMT-18017: Refactor placeholder pull secret
  controlplane/internal/auth/auth.go
  controlplane/internal/auth/auth_test.go
  controlplane/internal/controller/agentcontrolplane_controller.go
  controlplane/internal/controller/agentcontrolplane_controller_test.go
  util/util.go
Labels: lgtm, approved, jira/valid-reference, size/L

#44 MGMT-18277: add automatic release
  .github/workflows/release.yaml
Labels: approved, size/M, jira/valid-reference
