Repository openshift-assisted/cluster-api-provider-openshift-assisted, pull requests merged in 2025-02, with the labels that each got.

#76 NO-ISSUE: Update README.md and add CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
  test/ansible/run_test.yaml
Labels: lgtm, approved, size/M, jira/valid-reference

#79 add controlplane conditions
  controlplane/api/v1alpha2/condition_consts.go
  controlplane/api/v1alpha2/openshiftassistedcontrolplane_types.go
  controlplane/internal/controller/agentclusterinstall_controller.go
  controlplane/internal/controller/openshiftassistedcontrolplane_controller.go
  controlplane/internal/controller/openshiftassistedcontrolplane_controller_test.go
Labels: lgtm, approved, size/L

#80 MGMT-19876: Detect upgrade
  controlplane/api/v1alpha2/openshiftassistedcontrolplane_types.go
  controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_openshiftassistedcontrolplanes.yaml
  controlplane/internal/controller/openshiftassistedcontrolplane_controller.go
  controlplane/internal/controller/openshiftassistedcontrolplane_controller_test.go
  controlplane/internal/controller/suite_test.go
  controlplane/internal/upgrade/upgrade.go
  controlplane/internal/upgrade/upgrade_test.go
  controlplane/internal/workloadclient/workload_client.go
  controlplane/main.go
  util/util.go
Labels: lgtm, approved, jira/valid-reference, size/L

#81 MGMT-19877: Trigger workload cluster upgrade
  controlplane/internal/controller/openshiftassistedcontrolplane_controller.go
  controlplane/internal/upgrade/upgrade.go
  controlplane/internal/upgrade/upgrade_test.go
Labels: lgtm, approved, jira/valid-reference, size/L
