Repository openshift-assisted/cluster-api-provider-openshift-assisted, pull requests merged in 2025-04, with the labels that each got.

#117 MGMT-18437: Use consumer label on ACI for data collection
  controlplane/internal/controller/clusterdeployment_controller.go
  controlplane/internal/controller/clusterdeployment_controller_test.go
  go.mod
  go.sum
  vendor/github.com/openshift/assisted-service/api/hiveextension/v1beta1/agentclusterinstall_types.go
  vendor/github.com/openshift/assisted-service/models/bundle.go
  vendor/github.com/openshift/assisted-service/models/cluster.go
  vendor/github.com/openshift/assisted-service/models/cluster_validation_id.go
  vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
  vendor/github.com/openshift/assisted-service/models/host_validation_id.go
  vendor/github.com/openshift/assisted-service/models/install_cmd_request.go
  vendor/github.com/openshift/assisted-service/models/monitored_operator.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference, size/L

#118 bugfix: change image name in tests
  test/playbooks/roles/build_images/tasks/main.yaml
  test/playbooks/roles/components_install/tasks/main.yaml
Labels: size/XS, approved

#120 e2e-tests: update bmo version and make some conditions more robust
  test/e2e/manifests/bmo/kustomization.yaml
  test/playbooks/roles/assert_install/tasks/main.yaml
  test/playbooks/roles/assert_upgrade/tasks/main.yaml
  test/playbooks/roles/components_install/tasks/main.yaml
Labels: size/S, approved

#119 Clean up resource labels, names, and namespaces
  Makefile
  bootstrap-components.yaml
  bootstrap/config/default/kustomization.yaml
  bootstrap/config/default/manager_auth_proxy_patch.yaml
  bootstrap/config/default/manager_config_patch.yaml
  bootstrap/config/manager/manager.yaml
  bootstrap/config/prometheus/monitor.yaml
  bootstrap/config/rbac/auth_proxy_client_clusterrole.yaml
  bootstrap/config/rbac/auth_proxy_role.yaml
  bootstrap/config/rbac/auth_proxy_role_binding.yaml
  bootstrap/config/rbac/auth_proxy_service.yaml
  bootstrap/config/rbac/leader_election_role.yaml
  bootstrap/config/rbac/leader_election_role_binding.yaml
  bootstrap/config/rbac/openshiftassistedconfig_editor_role.yaml
  bootstrap/config/rbac/openshiftassistedconfig_viewer_role.yaml
  bootstrap/config/rbac/openshiftassistedconfigtemplate_editor_role.yaml
  bootstrap/config/rbac/openshiftassistedconfigtemplate_viewer_role.yaml
  bootstrap/config/rbac/role.yaml
  bootstrap/config/rbac/role_binding.yaml
  bootstrap/config/rbac/service_account.yaml
  controlplane-components.yaml
  controlplane/config/default/kustomization.yaml
  controlplane/config/default/manager_auth_proxy_patch.yaml
  controlplane/config/default/manager_config_patch.yaml
  controlplane/config/manager/manager.yaml
  controlplane/config/prometheus/monitor.yaml
  controlplane/config/rbac/auth_proxy_client_clusterrole.yaml
  controlplane/config/rbac/auth_proxy_role.yaml
  controlplane/config/rbac/auth_proxy_role_binding.yaml
  controlplane/config/rbac/auth_proxy_service.yaml
  controlplane/config/rbac/controlplane_openshiftassistedcontrolplane_editor_role.yaml
  controlplane/config/rbac/controlplane_openshiftassistedcontrolplane_viewer_role.yaml
  controlplane/config/rbac/leader_election_role.yaml
  controlplane/config/rbac/leader_election_role_binding.yaml
  controlplane/config/rbac/role.yaml
  controlplane/config/rbac/role_binding.yaml
  controlplane/config/rbac/service_account.yaml
Labels: lgtm, size/XL, approved

#122 manifest: add namespace to role
  controlplane-components.yaml
  controlplane/config/rbac/leader_election_role.yaml
Labels: size/XS, approved

#123 remove rbac auth proxy from manifests
  bootstrap-components.yaml
  bootstrap/config/default/kustomization.yaml
  bootstrap/config/default/manager_auth_proxy_patch.yaml
  bootstrap/config/rbac/auth_proxy_client_clusterrole.yaml
  bootstrap/config/rbac/auth_proxy_role.yaml
  bootstrap/config/rbac/auth_proxy_role_binding.yaml
  bootstrap/config/rbac/auth_proxy_service.yaml
  bootstrap/config/rbac/kustomization.yaml
  controlplane-components.yaml
  controlplane/config/default/kustomization.yaml
  controlplane/config/default/manager_auth_proxy_patch.yaml
  controlplane/config/rbac/auth_proxy_client_clusterrole.yaml
  controlplane/config/rbac/auth_proxy_role.yaml
  controlplane/config/rbac/auth_proxy_role_binding.yaml
  controlplane/config/rbac/auth_proxy_service.yaml
  controlplane/config/rbac/kustomization.yaml
Labels: lgtm, size/XL, approved

#121 Use controllerutil for create or update
  assistedinstaller/clusterdeployment.go
  controlplane/internal/controller/clusterdeployment_controller.go
  controlplane/internal/controller/openshiftassistedcontrolplane_controller.go
  controlplane/internal/imageregistry/image_registry.go
  controlplane/internal/imageregistry/image_registry_test.go
  util/suite_test.go
  util/util.go
  util/util_test.go
Labels: lgtm, size/XL, approved

#125 remove limit for number of containers in containers.conf
  test/playbooks/roles/network_setup/tasks/main.yaml
Labels: lgtm, size/S, approved

#124 add action to build and push images
  .github/workflows/publish_images.yaml
  .github/workflows/release.yaml
Labels: lgtm, approved, size/M

#109 MGMT-19400 - create tag management flow to tag assisted installer components according to capbcoa versions
  .gitignore
  components.yaml
  hack/boilerplate.go.txt
  hack/versions-management/ansible_test_runner.py
  hack/versions-management/conftest.py
  hack/versions-management/core/clients/ansible_client.py
  hack/versions-management/core/clients/github_client.py
  hack/versions-management/core/clients/image_registry_client.py
  hack/versions-management/core/models/__init__.py
  hack/versions-management/core/models/artifact.py
  hack/versions-management/core/models/component.py
  hack/versions-management/core/models/snapshot.py
  hack/versions-management/core/models/snapshot_metadata.py
  hack/versions-management/core/models/version.py
  hack/versions-management/core/models/wrappers.py
  hack/versions-management/core/repositories/__init__.py
  hack/versions-management/core/repositories/components_repository.py
  hack/versions-management/core/repositories/release_candidates_repository.py
  hack/versions-management/core/repositories/version_repository.py
  hack/versions-management/core/services/ansible_test_runner_service.py
  hack/versions-management/core/services/service.py
  hack/versions-management/core/services/tag_reconciliation_service.py
  hack/versions-management/core/services/version_discovery_service.py
  hack/versions-management/core/utils/logging.py
  hack/versions-management/core/utils/yaml_loader.py
  hack/versions-management/requirements.txt
  hack/versions-management/tag_reconciler.py
  hack/versions-management/test/__init__.py
  hack/versions-management/test/assets/components.yaml
  hack/versions-management/test/assets/release-candidates.yaml
  hack/versions-management/test/assets/versions.yaml
  hack/versions-management/test/clients/test_ansible_client.py
  hack/versions-management/test/clients/test_github_client.py
  hack/versions-management/test/clients/test_image_registry_client.py
  hack/versions-management/test/repositories/test_release_repository.py
  hack/versions-management/test/repositories/test_version_repository.py
  hack/versions-management/test/services/test_ansible_test_runner_service.py
  hack/versions-management/test/services/test_tags_reconciliation_service.py
  hack/versions-management/test/services/test_version_discovery_service.py
  hack/versions-management/version_discovery.py
  test/e2e/manifests/infrastructure-operator/kustomization.yaml.j2
  test/playbooks/roles/components_install/tasks/main.yaml
  test/playbooks/run_test.yaml
Labels: lgtm, size/XXL, approved

#129 export env vars for makefile target
  Makefile
Labels: size/XS, approved

#127 add fast forwarding github action
  .github/workflows/fast_forward.yaml
Labels: lgtm, size/S, approved

#128 add backplane branch to build branches
  .github/workflows/publish_images.yaml
Labels: lgtm, size/XS, approved

#130 NO-ISSUE: separate image and version into two distinct vars in ansible
  hack/versions-management/core/clients/image_registry_client.py
  hack/versions-management/core/models/artifact.py
  hack/versions-management/core/services/ansible_test_runner_service.py
  hack/versions-management/core/services/version_discovery_service.py
  hack/versions-management/test/clients/test_image_registry_client.py
  hack/versions-management/test/services/test_ansible_test_runner_service.py
  hack/versions-management/test/services/test_version_discovery_service.py
  test/e2e/manifests/infrastructure-operator/kustomization.yaml.j2
  test/playbooks/roles/components_install/tasks/main.yaml
  test/playbooks/run_test.yaml
Labels: lgtm, approved, jira/valid-reference, size/L

#126 MGMT-19979: Propagate ClusterVersion upgrade status message
  controlplane/api/v1alpha2/condition_consts.go
  controlplane/internal/controller/openshiftassistedcontrolplane_controller.go
  controlplane/internal/controller/openshiftassistedcontrolplane_controller_test.go
  controlplane/internal/upgrade/mock_upgrade.go
  controlplane/internal/upgrade/upgrade.go
  controlplane/internal/upgrade/upgrade_test.go
Labels: lgtm, approved, jira/valid-reference, size/L

#138 do not place bootstrap sentinel file, as some distribution use read only filesystem in the required location
  bootstrap/internal/controller/agent_controller.go
Labels: lgtm, size/XS, approved

#139 add ADR for removing sentinel file
  README.md
  docs/adr/003-sentinel-file-not-implemented.md
Labels: approved, size/M

#136 ensure agent is not approved if one already exist with the same infraenv
  bootstrap/internal/controller/agent_controller.go
  bootstrap/internal/controller/agent_controller_test.go
Labels: lgtm, approved, size/L

#141 fix okd version parsing
  controlplane/internal/release/release.go
Labels: size/XS, approved

#140 split dockerfiles
  .github/workflows/publish_images.yaml
  .github/workflows/security-scan.yaml
  Dockerfile.bootstrap-provider
  Dockerfile.controlplane-provider
  Dockerfile.distrobox
  Dockerfile.j2
  Makefile
  README.md
Labels: lgtm, approved, size/L
