Repository openshift-assisted/cluster-api-provider-openshift-assisted, pull requests merged in 2025-05, with the labels that each got.

#146 Update dockerfiles to use approved images
  Dockerfile.bootstrap-provider
  Dockerfile.controlplane-provider
  Dockerfile.j2
Labels: lgtm, approved, size/M

#158 add specific dockerfile for github action publishing images
  .github/workflows/publish_images.yaml
Labels: size/XS, approved

#159 add variable for dockerfile in github action
  .github/workflows/publish_images.yaml
Labels: size/XS, approved

#160 add readme overview
  README.md
Labels: approved

#164 update agent only when necessary
  bootstrap/internal/controller/agent_controller.go
Labels: lgtm, size/S, approved

#166 use ubi path for dockerfile
  Dockerfile.bootstrap-provider
  Dockerfile.controlplane-provider
  Dockerfile.j2
Labels: lgtm, approved, size/M

#167 rename go module
  PROJECT
  README.md
  assistedinstaller/infraenv.go
  assistedinstaller/infraenv_test.go
  bootstrap/internal/controller/agent_controller.go
  bootstrap/internal/controller/agent_controller_test.go
  bootstrap/internal/controller/infraenv_controller.go
  bootstrap/internal/controller/infraenv_controller_test.go
  bootstrap/internal/controller/openshiftassistedconfig_controller.go
  bootstrap/internal/controller/openshiftassistedconfig_controller_test.go
  bootstrap/internal/controller/suite_test.go
  bootstrap/main.go
  controlplane/api/v1alpha2/openshiftassistedcontrolplane_types.go
  controlplane/internal/auth/auth.go
  controlplane/internal/controller/agentclusterinstall_controller.go
  controlplane/internal/controller/agentclusterinstall_controller_test.go
  controlplane/internal/controller/clusterdeployment_controller.go
  controlplane/internal/controller/clusterdeployment_controller_test.go
  controlplane/internal/controller/openshiftassistedcontrolplane_controller.go
  controlplane/internal/controller/openshiftassistedcontrolplane_controller_test.go
  controlplane/internal/controller/suite_test.go
  controlplane/internal/release/release_test.go
  controlplane/internal/upgrade/upgrade.go
  controlplane/internal/upgrade/upgrade_test.go
  controlplane/internal/version/openshift.go
  controlplane/internal/version/openshift_test.go
  controlplane/internal/workloadclient/workload_client.go
  controlplane/main.go
  go.mod
  pkg/containers/auth_test.go
  pkg/containers/extractor_test.go
  test/utils/unit.go
  util/util.go
Labels: lgtm, approved, size/L

#178 NO-ISSUE: added dry-run to ansible-test-runner and adjustments for prow
  hack/versions-management/core/services/version_discovery_service.py
Labels: lgtm, size/XS, approved, jira/valid-reference

#181 NO-ISSUE: add git remote origin in version discovery and test runner scripts
  hack/versions-management/ansible_test_runner.sh
  hack/versions-management/version_discovery.sh
Labels: lgtm, size/XS, approved, jira/valid-reference

#182 NO-ISSUE: versions management - move common git auth operations to gi…
  hack/versions-management/ansible_test_runner.sh
  hack/versions-management/github_auth.sh
  hack/versions-management/version_discovery.sh
Labels: lgtm, size/S, approved, jira/valid-reference

#184 Revert "Update release candidates"
  release-candidates.yaml
Labels: lgtm, size/XS, approved

#185 NO-ISSUE: versions management - set GITHUB_TOKEN environment variable to enable gh cli usage
  hack/versions-management/github_auth.sh
Labels: lgtm, size/XS, approved, jira/valid-reference

#187 use cherry-pick instead of fast-forward, due to diverging configuration on branches
  .github/workflows/cherry_pick.yaml
Labels: lgtm, size/XS, approved

#189 NO-ISSUE: versions management - moving github authentication logic to after the snapshot test to avoid token getting time out during the test
  hack/versions-management/ansible_test_runner.sh
Labels: lgtm, size/XS, approved, jira/valid-reference

#193 add identity to cherry-pick job
  .github/workflows/cherry_pick.yaml
Labels: lgtm, size/XS, approved

#202 increase timeout for linting
  Makefile
Labels: lgtm, size/XS, approved

#198 Add renovate.json to prevent dependency updates
  renovate.json
Labels: lgtm, size/XS, approved

#203 remove cherry picking backplane branch
  .github/workflows/cherry_pick.yaml
Labels: lgtm, approved, size/M

#204 NO-ISSUE: versions management - retest current snapshot
  release-candidates.yaml
Labels: lgtm, size/XS, approved, jira/valid-reference

#207 NO-ISSUE: versions management - new version
  versions.yaml
Labels: lgtm, approved, size/M, jira/valid-reference

#208 NO-ISSUE: versions management - fix tags reconciler dry run script
  hack/versions-management/tag_reconciler.sh
Labels: lgtm, size/XS, approved, jira/valid-reference

#209 NO-ISSUE: versions management - fix tags reconciler dry run script
  hack/versions-management/tag_reconciler.sh
Labels: lgtm, size/XS, approved, jira/valid-reference

#210 NO-ISSUE: versions management - remove versions.yaml
  versions.yaml
Labels: lgtm, approved, size/M, jira/valid-reference
