Repository openshift-assisted/cluster-api-provider-openshift-assisted, pull requests merged in 2025-07, with the labels that each got.

#311 NO-ISSUE: versions management - removing outdated versions
  release-candidates.yaml
Labels: lgtm, size/XXL, approved, jira/valid-reference

#306 NO-ISSUE: Add slack notification when merge pipeline failed
  .tekton/cluster-api-provider-openshift-assisted-bootstrap-mce-29-push.yaml
  .tekton/cluster-api-provider-openshift-assisted-control-plane-mce-29-push.yaml
Labels: lgtm, approved, size/M, jira/valid-reference

#364 Ffwd backplane 2.10
  .github/workflows/sync-branch.yaml
  .tekton/cluster-api-provider-openshift-assisted-bootstrap-mce-210-pull-request.yaml
  .tekton/cluster-api-provider-openshift-assisted-bootstrap-mce-210-push.yaml
  .tekton/cluster-api-provider-openshift-assisted-control-plane-mce-210-pull-request.yaml
  .tekton/cluster-api-provider-openshift-assisted-control-plane-mce-210-push.yaml
  hack/branch
  renovate.json
Labels: lgtm, size/XXL, approved

#334 Mgmt 20930 expose install config
  controlplane/api/v1alpha2/openshiftassistedcontrolplane_types.go
  controlplane/internal/controller/clusterdeployment_controller.go
  controlplane/internal/controller/clusterdeployment_controller_test.go
  docs/getting_started.md
Labels: lgtm, approved, size/L
