Repository openshift-assisted/cluster-api-provider-openshift-assisted, pull requests merged in 2025-03, with the labels that each got.

#83 handle cluster upgrades with feedback from CVO
  Makefile
  controlplane/api/v1alpha2/condition_consts.go
  controlplane/internal/auth/auth.go
  controlplane/internal/controller/agentclusterinstall_controller.go
  controlplane/internal/controller/clusterdeployment_controller.go
  controlplane/internal/controller/openshiftassistedcontrolplane_controller.go
  controlplane/internal/controller/openshiftassistedcontrolplane_controller_test.go
  controlplane/internal/controller/suite_test.go
  controlplane/internal/release/constants.go
  controlplane/internal/release/release.go
  controlplane/internal/release/release_test.go
  controlplane/internal/release/suite_test.go
  controlplane/internal/upgrade/mock_upgrade.go
  controlplane/internal/upgrade/suite_test.go
  controlplane/internal/upgrade/upgrade.go
  controlplane/internal/upgrade/upgrade_test.go
  controlplane/internal/version/mock_version.go
  controlplane/internal/version/openshift.go
  controlplane/internal/version/openshift_test.go
  controlplane/internal/version/suite_test.go
  controlplane/internal/workloadclient/mock_clientgenerator.go
  controlplane/internal/workloadclient/workload_client.go
  controlplane/main.go
  examples/multi-node-example.yaml
  examples/sno-example.yaml
  external_mocks/mocks.go
  external_mocks/mocks_containerregistry.go
  go.mod
  pkg/containers/extrac_mock_test.go
  pkg/containers/extract_test.go
  pkg/containers/extractor.go
  pkg/containers/extractor_test.go
  pkg/containers/mock_containers.go
  pkg/containers/repository.go
  pkg/containers/types.go
  test/ansible/run_test.yaml
  test/e2e/manifests/infrastructure-operator/agentconfig.yaml
  util/test/tar_archive.go
  util/util.go
Labels: size/XXL, approved

#85 scale down controlplane nodes
  bootstrap/api/v1alpha1/openshiftassistedconfig_types.go
  bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_openshiftassistedconfigs.yaml
  bootstrap/internal/controller/openshiftassistedconfig_controller.go
  controlplane/api/v1alpha2/openshiftassistedcontrolplane_types.go
  controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_openshiftassistedcontrolplanes.yaml
  controlplane/internal/controller/openshiftassistedcontrolplane_controller.go
  controlplane/internal/controller/openshiftassistedcontrolplane_controller_test.go
  controlplane/internal/controller/suite_test.go
  go.mod
  test/e2e/manifests/infrastructure-operator/kustomization.yaml
  util/failuredomains/failure_domains.go
  util/failuredomains/failure_domains_test.go
  util/failuredomains/suite_test.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cluster-api/util/failuredomains/failure_domains.go
Labels: size/XL, approved

#89 MGMT-20105: Add rbac for managedclustersets/join
  controlplane-components.yaml
  controlplane/config/rbac/role.yaml
  controlplane/internal/controller/openshiftassistedcontrolplane_controller.go
Labels: lgtm, approved, size/M, jira/valid-reference

#88 NO-ISSUE: Explicitly set namespace in all multi-node example resources
  examples/multi-node-example.yaml
Labels: lgtm, size/XS, approved, jira/valid-reference

#91 generated latest manifests
  bootstrap-components.yaml
  controlplane-components.yaml
Labels: lgtm, approved, size/M

#87 MGMT-20102: Set clusterinstallref on clusterdeployment create
  assistedinstaller/clusterdeployment.go
  controlplane/internal/controller/clusterdeployment_controller.go
Labels: lgtm, size/S, approved, jira/valid-reference

#86 bugfix: IsDesiredVersion should make sure the desired version is right
  controlplane/internal/controller/openshiftassistedcontrolplane_controller.go
  controlplane/internal/upgrade/upgrade.go
  controlplane/internal/upgrade/upgrade_test.go
  test/ansible/run_test.yaml
Labels: size/S, approved

#92 bugfix: unavailable machines should not be negative
  controlplane/internal/controller/openshiftassistedcontrolplane_controller.go
Labels: size/XS, approved

#93 MGMT-20110: upgrade infra operator manifest version
  test/e2e/manifests/infrastructure-operator/kustomization.yaml
Labels: lgtm, size/XS, approved, jira/valid-reference

#98 add coderabbit config
  .coderabbit.yaml
Labels: size/XS, approved

#100 improve e2e tests
  examples/multinode-example.yaml
  test/ansible/run_test.yaml
Labels: size/S, approved

#96 MGMT-20013: Allow user-specified capabilities when installing a workload cluster
  controlplane/api/v1alpha2/openshiftassistedcontrolplane_types.go
  controlplane/api/v1alpha2/zz_generated.deepcopy.go
  controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_openshiftassistedcontrolplanes.yaml
  controlplane/internal/controller/clusterdeployment_controller.go
  controlplane/internal/controller/clusterdeployment_controller_test.go
  test/utils/unit.go
Labels: lgtm, approved, jira/valid-reference, size/L

#101 MGMT-20175: mark upgrade in progress status earlier
  controlplane/internal/controller/openshiftassistedcontrolplane_controller.go
  controlplane/internal/controller/openshiftassistedcontrolplane_controller_test.go
Labels: approved, size/M, jira/valid-reference

#105 update published manifests
  bootstrap-components.yaml
  controlplane-components.yaml
Labels: approved, size/L

#106 add makefile target for published manifests
  Makefile
Labels: size/XS, approved

#107 show diff when checking for generated files before returning error
  .gitignore
  Makefile
Labels: size/XS, approved

#103 MGMT-20162: improve usage of CreateOrUpdate
  controlplane/internal/controller/clusterdeployment_controller.go
  controlplane/internal/controller/openshiftassistedcontrolplane_controller.go
  controlplane/internal/controller/utils.go
  util/suite_test.go
  util/util.go
  util/util_test.go
Labels: lgtm, approved, jira/valid-reference, size/L

#102 MGMT-20067: remove arch suffix from Spec.DistributionVersion
  bootstrap/internal/controller/agent_controller_test.go
  bootstrap/internal/controller/infraenv_controller_test.go
  bootstrap/internal/controller/openshiftassistedconfig_controller_test.go
  bootstrap/main_test.go
  controlplane/internal/controller/clusterdeployment_controller.go
  controlplane/internal/controller/clusterdeployment_controller_test.go
  controlplane/internal/controller/openshiftassistedcontrolplane_controller.go
  controlplane/internal/controller/openshiftassistedcontrolplane_controller_test.go
  controlplane/internal/release/release.go
  controlplane/internal/upgrade/mock_upgrade.go
  controlplane/internal/upgrade/upgrade.go
  controlplane/internal/upgrade/upgrade_test.go
  examples/multinode-example.yaml
  examples/sno-example.yaml
  test/ansible/run_test.yaml
  test/utils/unit.go
Labels: approved, do-not-merge/hold, jira/valid-reference, size/L

#99 add ADR for architectural decision that diverge from CAPI contracts
  README.md
  docs/adr/001-distribution-version.md
  docs/adr/002-distribution-version-upgrades.md
Labels: lgtm, approved, size/M

#108 MGMT-20194: split ansible tests in roles
  Makefile
  README.md
  examples/multinode-example.yaml.j2
  examples/sno-example.yaml.j2
  test/ansible-requirements.yaml
  test/ansible/run_test.yaml
  test/e2e/libvirt/network-bmh.xml.j2
  test/playbooks/cleanup.yaml
  test/playbooks/inventories/remote_host.yaml
  test/playbooks/roles/assert_install/tasks/main.yaml
  test/playbooks/roles/assert_upgrade/defaults/main.yaml
  test/playbooks/roles/assert_upgrade/tasks/main.yaml
  test/playbooks/roles/baremetal_emulation/tasks/main.yaml
  test/playbooks/roles/bmh_setup/tasks/main.yaml
  test/playbooks/roles/build_images/tasks/main.yaml
  test/playbooks/roles/cleanup/tasks/main.yaml
  test/playbooks/roles/cluster_install/tasks/main.yaml
  test/playbooks/roles/components_install/tasks/main.yaml
  test/playbooks/roles/kind_setup/defaults/main.yaml
  test/playbooks/roles/kind_setup/tasks/main.yaml
  test/playbooks/roles/network_setup/tasks/main.yaml
  test/playbooks/roles/sourcecode_setup/defaults/main.yaml
  test/playbooks/roles/sourcecode_setup/tasks/main.yaml
  test/playbooks/roles/system_dependencies/defaults/main.yaml
  test/playbooks/roles/system_dependencies/tasks/main.yaml
  test/playbooks/run_test.yaml
Labels: size/XL, approved, jira/valid-reference

#111 add pip to test system dependencies
  test/playbooks/roles/system_dependencies/defaults/main.yaml
Labels: size/XS, approved

#113 add jmespath as dependency for e2e ansible playbook
  test/playbooks/roles/system_dependencies/tasks/main.yaml
Labels: size/XS, approved

#115 remove json_query dependency from e2e tests
  test/playbooks/roles/components_install/tasks/main.yaml
  test/playbooks/roles/system_dependencies/tasks/main.yaml
Labels: size/S, approved

#114 add security scan
  .github/workflows/release.yaml
  .github/workflows/security-scan.yaml
  .trivy.yaml
  Makefile
  bootstrap-components.yaml
  bootstrap/config/manager/kustomization.yaml
  controlplane-components.yaml
  controlplane/config/manager/kustomization.yaml
Labels: approved, size/M
