Repository openshift-assisted/cluster-api-provider-openshift-assisted, pull requests merged in 2025-08, with the labels that each got.

#411 Update trivy-action to v0.32.0 in security-scan.yaml
  .github/workflows/security-scan.yaml
Labels: lgtm, size/S, approved

#410 [backplane-2.9] MGMT-20930: expose installConfig override through CAPOA
  controlplane/api/v1alpha2/openshiftassistedcontrolplane_types.go
  controlplane/internal/controller/clusterdeployment_controller.go
  controlplane/internal/controller/clusterdeployment_controller_test.go
  docs/getting_started.md
Labels: lgtm, approved, jira/valid-reference, size/L

#416 add labels to dockerfiles
  Dockerfile.bootstrap-provider
  Dockerfile.controlplane-provider
  Dockerfile.j2
Labels: lgtm, approved, size/M
