Repository openshift-assisted/cluster-api-provider-openshift-assisted, pull requests merged in 2025-06, with the labels that each got.

#249 ACM-21350: Enable CGO for FIPS compliance
  Dockerfile.bootstrap-provider
  Dockerfile.controlplane-provider
  Dockerfile.j2
Labels: lgtm, size/XS, approved, jira/valid-reference

#247 MGMT-20825: add discovery ignition annotation
  assistedinstaller/infraenv.go
  assistedinstaller/infraenv_test.go
  bootstrap/api/v1alpha1/openshiftassistedconfig_types.go
Labels: lgtm, approved, jira/valid-reference, size/L

#254 MGMT-20825: add annotation to expose discovery config override
  assistedinstaller/infraenv.go
  assistedinstaller/infraenv_test.go
  bootstrap/api/v1alpha1/openshiftassistedconfig_types.go
Labels: lgtm, approved, jira/valid-reference, size/L

#246 Mgmt 20822 kernelargs to coreos installer args
  assistedinstaller/infraenv.go
  bootstrap/internal/controller/agent_controller.go
  bootstrap/internal/controller/agent_controller_test.go
  bootstrap/internal/controller/openshiftassistedconfig_controller_test.go
Labels: lgtm, approved, size/M

#256 Mgmt 20822 kernelargs to coreos installer args backport 2.9
  assistedinstaller/infraenv.go
  bootstrap/internal/controller/agent_controller.go
  bootstrap/internal/controller/agent_controller_test.go
  bootstrap/internal/controller/openshiftassistedconfig_controller_test.go
Labels: lgtm, approved, size/M
